#!/bin/sh
# 
# ▓█████▄  ▄▄▄▄    ▄▄▄        ▄████ 
# ▒██▀ ██▌▓█████▄ ▒████▄     ██▒ ▀█▒
# ░██   █▌▒██▒ ▄██▒██  ▀█▄  ▒██░▄▄▄░
# ░▓█▄   ▌▒██░█▀  ░██▄▄▄▄██ ░▓█  ██▓
# ░▒████▓ ░▓█  ▀█▓ ▓█   ▓██▒░▒▓███▀▒
#  ▒▒▓  ▒ ░▒▓███▀▒ ▒▒   ▓▒█░ ░▒   ▒ 
#  ░ ▒  ▒ ▒░▒   ░   ▒   ▒▒ ░  ░   ░ 
#  ░ ░  ░  ░    ░   ░   ▒   ░ ░   ░ 
#    ░     ░            ░  ░      ░ 
#  ░            ░                   

num_quotes=70
rand=$[ ( $RANDOM % $num_quotes ) + 1 ]
 
case $rand in
    1) quote="mort: use the man pages";;
    2) quote="geoip /always/ lies";;
    3) quote="only jews make you pay for the salad";;
    4) quote="old enough to bleed, old enough to breed, old enough to pee, old enough for me. old enough to count, old enough to mount";;
    5) quote="books are the dumbbells of pseudo-intellectuals";;
    6) quote="nothing cures you from religion than a religious school";;
    7) quote="why do I enjoy the smell of my own ballsack?";;
    8) quote="aparently I did a shitty job at wiping last night and now I had to pay the price. there was a dried poop cherry attached to my butt-beard. cause it takes me 2 hours to fire up my brain. the pain of ripping it out though. I now understand the pain of tar and feathering";;
    9) quote="not porn though";;
    10) quote="if you pee sitting down, you're like 70% female";;
    11) quote="we should hunt for ymbx";;
    12) quote="your mothers asshole was raw after I was done with her.";;
    13) quote="son, here's the difference: people care about my dick";;
    14) quote="ISO art only art";;
    15) quote="nope. nope. nope. not touching clowns";;
    16) quote="goddamn I broke it";;
    17) quote="como estas mi negro judio amigo";;
    18) quote="xero: wtf are you talking about?";;
    19) quote="just reichrolling a bit";;
    20) quote="rocx: are you asexual?";;
    21) quote="that reply\nis the reply of a man who's given up";;
    22) quote="not too long before he's going to oregon to find bigfoot";;
    23) quote="I've done a server side replacement for you, where h a s k e l l always gets substituted with anal";;
    24) quote="brb /'ing wrists";;
    25) quote="I think not. I don't want jewphilis";;
    26) quote="said the sex shop salesman";;
    27) quote="you wouldn't know the difference between her butthole and her elbow";;
    28) quote="can't go from virgin to fucking a masterslutsie";;
    29) quote="rocx: my nigga";;
    30) quote="mein niglet";;
    31) quote="bashism";;
    32) quote="so I ordered a bit of jew-horn on the black market";;
    33) quote="jew-snout is suppposedly an aphrodisiac";;
    34) quote="dafuq did I just type";;
    35) quote="well, I'm not hurting anyone. Truth be told, I've had some side-effects. I've sat for hours and hours just stroking dollar bills. I do these creepy coughs too: "my precious *cough* goldblum *cough*"";;
    36) quote="goddamnit guys";;
    37) quote="if I wanted a hairless chick, I'd go to an elementary school";;
    38) quote="the level of faggyness in this channel is disturbing. I blame ymbx";;
    39) quote="flood control is tighter than a ticks asshole";;
    40) quote="xero: master level rice";;
    41) quote="why do we even need to buy lube? I just blow my nose on my dick. natures lube. also, if it has a "lasting smell", you need to brush your teeth more often";;
    42) quote="he is the male version of an unfuckable hag over 60";;
    43) quote="when it's flacid, it says \"AIDS\"";;
    44) quote="if you're lazy, openbsd is for you";;
    45) quote="ymbx is totally gay. he's so far in the closet he's reached narnia";;
    46) quote="dami: stop telling people to use shit software. you're basically taking a shit on unix philosophy";;
    47) quote="I like my women like I like my wine, locked up in my dark basement";;
    48) quote="surprisingly I don't like cats";;
    49) quote="I got statically compiled musl";;
    50) quote="I was at it a little harder than I should've, and I think I cut my foreskin";;
    51) quote="lets write a \"pretty ls\". one with all the fancy colors and shit. TL;DR alias ls=\"ls --colors=auto\"";;
    52) quote="rate my neckbeard. \nRATE IT MOTHERFUCKER! \nYOUR VALIDATION IS ALL THAT MATTERS TO ME";;
    53) quote="I am boss nigger";;
    54) quote="listen rocx, \nthis is what's on the agenda for today; \njerk off, eat icecream \nno \n I haven't decided the order yet \nI might as well have done that \nthe last icecream I ate tasted like shit \nthe swiss may know how to make chocolate, but not icecream";;
    55) quote="PETA == #1 animal snuff video producer";;
    56) quote="as your bro \nI give you this advice \ndon't eat chipotle";;
    57) quote="I DON'T WANNA TALK ABOUT THIS ANYMORE FUCKING TERRORIST COMMIE BOB DYLAN";;
    58) quote="rocx and fro in a cage \nmay the best of you win \ndon't worry \nif you're meat, fro will back away";;
    59) quote="fro: are you hopped up on sugar again?";;
    60) quote="rocx: have you ever considered joining the KKK?";;
    61) quote="I ... I ... I'm reading the busybox/editors/vi.c";;
    62) quote="thanks arch";;
    63) quote="rocx: can entropy be reversed?";;
    64) quote="well thank god for our tech support wizard z3bra";;
    65) quote="we can make jmbi's grandpa's dog the masco";;
    66) quote="just get venam out, and nuke the entire shit to pieces";;
    67) quote="vypr, I'm not a meanie";;
    68) quote="z3bra has a horrible habit of putting return; in his void functions";;
    69) quote="the most weird thing I've ever done is this chick who was into butt-firsting";;
    70) quote="what, don't you have root access to your system?";;
esac

printf '%b\n' "$quote" | fmt -80
