#!/bin/sh
# 
# ▓█████▄  ▄▄▄▄    ▄▄▄        ▄████ 
# ▒██▀ ██▌▓█████▄ ▒████▄     ██▒ ▀█▒
# ░██   █▌▒██▒ ▄██▒██  ▀█▄  ▒██░▄▄▄░
# ░▓█▄   ▌▒██░█▀  ░██▄▄▄▄██ ░▓█  ██▓
# ░▒████▓ ░▓█  ▀█▓ ▓█   ▓██▒░▒▓███▀▒
#  ▒▒▓  ▒ ░▒▓███▀▒ ▒▒   ▓▒█░ ░▒   ▒ 
#  ░ ▒  ▒ ▒░▒   ░   ▒   ▒▒ ░  ░   ░ 
#  ░ ░  ░  ░    ░   ░   ▒   ░ ░   ░ 
#    ░     ░            ░  ░      ░ 
#  ░            ░                   

_MAX=105
_RAND=`(od -D -N4 < /dev/urandom | tr -cd '[:digit:]'  ; echo " % $_MAX") | bc`

case $_RAND in
    1) _Q="mort: use the man pages";;
    2) _Q="geoip /always/ lies";;
    3) _Q="only jews make you pay for the salad";;
    4) _Q="old enough to bleed, old enough to breed, old enough to pee, old enough for me. old enough to count, old enough to mount";;
    5) _Q="books are the dumbbells of pseudo-intellectuals";;
    6) _Q="nothing cures you from religion than a religious school";;
    7) _Q="why do I enjoy the smell of my own ballsack?";;
    8) _Q="aparently I did a shitty job at wiping last night and now I had to pay the price. there was a dried poop cherry attached to my butt-beard. cause it takes me 2 hours to fire up my brain. the pain of ripping it out though. I now understand the pain of tar and feathering";;
    9) _Q="not porn though";;
    10) _Q="if you pee sitting down, you're like 70% female";;
    11) _Q="we should hunt for ymbx";;
    12) _Q="your mothers asshole was raw after I was done with her.";;
    13) _Q="son, here's the difference: people care about my dick";;
    14) _Q="ISO art only art";;
    15) _Q="nope. nope. nope. not touching clowns";;
    16) _Q="goddamn I broke it";;
    17) _Q="como estas mi negro judio amigo";;
    18) _Q="xero: wtf are you talking about?";;
    19) _Q="just reichrolling a bit";;
    20) _Q="rocx: are you asexual?";;
    21) _Q="that reply\nis the reply of a man who's given up";;
    22) _Q="not too long before he's going to oregon to find bigfoot";;
    23) _Q="I've done a server side replacement for you, where h a s k e l l always gets substituted with anal";;
    24) _Q="brb /'ing wrists";;
    25) _Q="I think not. I don't want jewphilis";;
    26) _Q="said the sex shop salesman";;
    27) _Q="you wouldn't know the difference between her butthole and her elbow";;
    28) _Q="can't go from virgin to fucking a masterslutsie";;
    29) _Q="rocx: my nigga";;
    30) _Q="mein niglet";;
    31) _Q="bashism";;
    32) _Q="so I ordered a bit of jew-horn on the black market";;
    33) _Q="jew-snout is suppposedly an aphrodisiac";;
    34) _Q="dafuq did I just type";;
    35) _Q="well, I'm not hurting anyone. Truth be told, I've had some side-effects. I've sat for hours and hours just stroking dollar bills. I do these creepy coughs too: \"my precious *cough* goldblum *cough*\"";;
    36) _Q="goddamnit guys";;
    37) _Q="if I wanted a hairless chick, I'd go to an elementary school";;
    38) _Q="the level of faggyness in this channel is disturbing. I blame ymbx";;
    39) _Q="flood control is tighter than a ticks asshole";;
    40) _Q="xero: master level rice";;
    41) _Q="why do we even need to buy lube? I just blow my nose on my dick. natures lube. also, if it has a \"lasting smell\", you need to brush your teeth more often";;
    42) _Q="he is the male version of an unfuckable hag over 60";;
    43) _Q="when it's flacid, it says \"AIDS\"";;
    44) _Q="if you're lazy, openbsd is for you";;
    45) _Q="ymbx is totally gay. he's so far in the closet he's reached narnia";;
    46) _Q="dami: stop telling people to use shit software. you're basically taking a shit on unix philosophy";;
    47) _Q="I like my women like I like my wine, locked up in my dark basement";;
    48) _Q="surprisingly I don't like cats";;
    49) _Q="I got statically compiled musl";;
    50) _Q="I was at it a little harder than I should've, and I think I cut my foreskin";;
    51) _Q="lets write a \"pretty ls\". one with all the fancy colors and shit.";;
    52) _Q="rate my neckbeard. \nRATE IT MOTHERFUCKER! \nYOUR VALIDATION IS ALL THAT MATTERS TO ME";;
    53) _Q="I am boss nigger";;
    54) _Q="listen rocx, \nthis is what's on the agenda for today; \njerk off, eat icecream \nno \nI haven't decided the order yet \nI might as well have done that \nthe last icecream I ate tasted like shit \nthe swiss may know how to make chocolate, but not icecream";;
    55) _Q="PETA == #1 animal snuff video producer";;
    56) _Q="as your bro \nI give you this advice \ndon't eat chipotle";;
    57) _Q="I DON'T WANNA TALK ABOUT THIS ANYMORE FUCKING TERRORIST COMMIE BOB DYLAN";;
    58) _Q="rocx and fro in a cage \nmay the best of you win \ndon't worry \nif you're meat, fro will back away";;
    59) _Q="fro: are you hopped up on sugar again?";;
    60) _Q="rocx: have you ever considered joining the KKK?";;
    61) _Q="I ... I ... I'm reading the busybox/editors/vi.c";;
    62) _Q="thanks arch";;
    63) _Q="rocx: can entropy be reversed?";;
    64) _Q="well thank god for our tech support wizard z3bra";;
    65) _Q="we can make jmbi's grandpa's dog the masco";;
    66) _Q="just get venam out, and nuke the entire shit to pieces";;
    67) _Q="vypr, I'm not a meanie";;
    68) _Q="z3bra has a horrible habit of putting return; in his void functions";;
    69) _Q="the most weird thing I've ever done is this chick who was into butt-firsting";;
    70) _Q="what, don't you have root access to your system?";;
    71) _Q="if you care what another guy is wearing, you're like 87% gay";;
    72) _Q="the only acceptable reason to fuck a clean shaven pussy is pedo or chemo";;
    73) _Q="my shits are as reliable as german trains";;
    74) _Q="computer science is just a international badge of \"I can take a dick up my ass for a year or two\"";;
    75) _Q="tbh I haven't met anyone who talks about haskell who aren't a pseudo intellectual";;
    76) _Q="every professor has a major stick up their ass";;
    77) _Q="z3bra: it's the curse of the *nix community \neveryone takes it as a personal attack when they're told their wrong";;
    78) _Q="int fcn() { return fcn(); } \nrecursive enough for you z3bra?";;
    79) _Q="if I get a hold of my cousin \nI'll optimize the recursion";;
    80) _Q="oxa: black stylesheets matter";;
    81) _Q="and I just figured out why wifi is always so bad on android \nwpa_supplicant";;
    82) _Q="the rule is simple; don't be an asshole";;
    83) _Q="I was told someone was talking about C++ \nso I decided to take some time out of my day to shit all over it";;
    84) _Q="it's like the pot of gold at the end of a faggy rainbow";;
    85) _Q="ssh fro@buttfuckers.r.us 'mount /dev/mother'";;
    86) _Q="put on your big girl pants and look like a grown man though";;
    87) _Q="and use the back camera \nnone of grainy front facing camera shit \nfull quality for maximum stencil pleasure \nI wanna be able to see the remains of that egg salad sandwich you ate last thursday";;
    88) _Q="the dcat always uses 80x24";;
    89) _Q="they're just trying to clean up the clusterfuck that is linux \nso that you can legally put it in a car without wondering if the wheels will fly off";;
    90) _Q="tbh what I'm most afraid of is parasites, ticks, and mosquitos";;
    91) _Q="calm down diabeto";;
    92) _Q="but every once in a while there's a shimmer of light in the dark hotkinkyjo-esque abyss that is github";;
    93) _Q="anyway, it's 29˚ here \nI'm gonna go sit in the fridge or something";;
    94) _Q="guys pls \nI live in redneckville, it takes like 2.5 secs to update the frame \nI type out these sentences before they show up on the screen";;
    95) _Q="I was gonna try to convince you guys I had no idea who hitler is \nand that I was talking about chaplin \nbut my pizza arrived and I can't be bothered anymore";;
    96) _Q="wow \nsounds like he hit the lottery on subhumanness";;
    97) _Q="okay lets not start a retarded discussion on whether or not alcohol is bad \nif you got 3 brain cells, you know it's bad for you";;
    98) _Q="like this is the kind of shit I expect to be scribbled at the 7/11 bathroom in a poor neighborhood";;
    99) _Q="new rules guys \nfro is IRC god";;
    100) _Q="dcattu (drone@fbi.gov) has joined #unix";;
    101) _Q="dcat is short for mr bojangle";;
    102) _Q="stop freaking out \nyou drank a little bit of pee \nit's not the end of the world";;
    103) _Q="when someone says \"I hate drama\" \nthey secretly love it";;
    104) _Q="did someone say oxygen thief?";;
    105) _Q="yeah, nature is nice and all \nbut it lacks swaztikas";;
esac

printf '%b\n' "$_Q" | fmt -80
